apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DATABASE_NAME: {{ .Values.postgres.database | quote }}
  DATABASE_USERNAME: {{ .Values.postgres.username | quote }}
  DATABASE_PASSWORD: {{ .Values.postgres.password | quote }}