name: BACKUP VIA SSH

on:
  schedule:
    - cron: '0 2 1,8,15,22 * *'
  workflow_dispatch:

jobs:
  backup_via_ssh:
    # Runs if variable is missing OR not equal to 'false'
    if: ${{ vars.ENABLE_DB_BACKUP != 'false' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Backup on Remote Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 68.233.96.154
          username: bigwiz
          port: 2198
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Connecting to server to run backup..."

            source ~/.zshrc

            cd /home/bigwiz/apps/bitmutex-website

            echo "Starting scheduled backup process..."

            pnpm run backup

            echo "Backup script finished."