name: BACKUP VIA SSH

on:
  schedule:
    - cron: '0 2 1,8,15,22 * *'  # Runs at 2:00 AM UTC on the 1st, 8th, 15th, and 22nd of every month.
  workflow_dispatch:

jobs:
  backup_via_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Backup on Remote Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 68.233.96.154
          username: bigwiz
          port: 2198 # Explicitly targets your custom SSH port
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
              echo "Connecting to server to run backup..."
              ssh -o StrictHostKeyChecking=no ubuntu@$SSH_HOST << 'EOF'
                echo "Starting scheduled backup process..."
                
                source ~/.zshrc

                # Navigate to the application root directory
                cd /home/bigwiz/apps/bitmutex-website
                
                # Run the backup script
                echo "Executing pnpm run backup..."
                # pnpm run backup # disabled here, as it is currently done via server cron
                
                echo "Backup script finished."
              EOF