name: SONAR_SCAN

on:
  # 1. Allows manual triggering directly from the Actions dashboard tab
  workflow_dispatch:

  # 2. Triggers ONLY when you push version tags matching vX.X.X
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Matches v1.0.0, v2.1.3-beta, etc.
  
  # 3. Triggers on pull requests targeted at any branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}